name: Generate notebook diff

on: ['pull_request']

jobs:
    check-diff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.6'
            
            - name: Install requirements
              run: pip3 install nbdime

            - name: Run diff
              run: nbdiff ${{ github.event.pull_request.base.ref }} > diff.log

            - name: Get comment body
              run: |
                body=$(cat diff.log)
                body="${body//'%'/'%25'}"
                body="${body//$'\n'/'%0A'}"
                body="${body//$'\r'/'%0D'}" 
                echo ::set-output name=body::$body

            - name: Create comment
              uses: peter-evans/create-or-update-comment@v1
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: ${{ steps.get-comment-body.outputs.body }}
